Update bugflow.yml

diff --git a/.github/workflows/bugflow.yml b/.github/workflows/bugflow.yml
--- a/.github/workflows/bugflow.yml
+++ b/.github/workflows/bugflow.yml
@@ -2,12 +2,12 @@ name: RUBIX_PROD_TEST
 
 on:
   pull_request:
-    types: [labeled]   # Run only when a label is added to a PR
-  workflow_dispatch:   # Still allow manual trigger
+    types: [labeled]   # Trigger when a label is added to a PR
+  workflow_dispatch:   # Allow manual trigger
 
 jobs:
   build:
-    if: github.event.label.name == 'bug'   # Ensure it only runs if the label is 'bug'
+    if: github.event.label.name == 'bug'   # Run only if the label added is 'bug'
     runs-on: ubuntu-latest
 
     steps:
@@ -23,7 +23,7 @@ jobs:
           curl -O https://sfc-repo.snowflakecomputing.com/snowsql/bootstrap/1.3/linux_x86_64/snowsql-1.3.2-linux_x86_64.bash
           SNOWSQL_DEST=~/bin SNOWSQL_LOGIN_SHELL=~/.profile bash snowsql-1.3.2-linux_x86_64.bash
 
-      - name: prepare user private Key
+      - name: Prepare user private Key
         run: |
           printf '%s\n' "${{ secrets.SF_DW_PROD_TEST_USER_PRIVATE_KEY }}" > ./private_key.pem
 
@@ -76,8 +76,7 @@ jobs:
                 -f "$file" \
                 -d ${{ secrets.SF_DW_PROD_TEST_DB }} \
                 -r ${{ secrets.SF_DW_PROD_TEST_ROLE }} \
-                -w ${{ secrets.SF_DW_PROD_TEST_WH }} \
-                -o log_level=DEBUG || { echo "Failed executing $file"; exit 1; }
+                -w ${{ secrets.SF_DW_PROD_TEST_WH }} || { echo "Failed executing $file"; exit 1; }
             else
               echo "File $file does not exist. Skipping."
             fi
